#!/usr/bin/env bash
# Add this file to .git/hooks/ and change mode to execute with the following
#
#   mv tools/pre-commit .git/hooks/
#   chmod +x .git/hooks/pre-commit

# For each changed python file run Isort Black 
for FILE in $(git status --short | cut -d 'M' -f 2)
do
  if [[ $FILE == *.py ]]; then
    if [[ $FILE == "__init__.py" ]]; then
      continue
    fi
    echo " Formating $FILE"
    echo "   Black"
    pipenv run black -l 120 -t py37 $FILE &> /dev/null
    echo "   Isort"
    pipenv run isort -y $FILE
  fi
done

# If any changes from Black or Isort add to commit.
echo " Add all"
git add *

# For each changed python file run Pylint
for FILE in $(git status --short | cut -d 'M' -f 2)
do
  if [[ $FILE =~ \.py$ ]]; then
    echo "ﴫ Pylint: $FILE"
    pipenv run pylint $FILE
  fi
done
exit 0